apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-run-as-nonroot
  namespace: sa-p8
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: require-non-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Los contenedores deben ejecutarse sin privilegios de root."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  runAsNonRoot: true