apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-resource-limits
  namespace: sa-p8
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: require-cpu-and-memory-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Cada contenedor debe definir limites de CPU y memoria."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"